apiVersion: container.gcp.crossplane.io/v1beta1
kind: GKECluster
metadata:
  name: devops-toolkit
spec:
  forProvider:
    location: europe-west3
    initialClusterVersion: latest

---

apiVersion: container.gcp.crossplane.io/v1alpha1
kind: NodePool
metadata:
  name: devops-toolkit
spec:
  forProvider:
    locations:
    - europe-west3-a
    - europe-west3-b
    - europe-west3-c
    clusterRef:
      name: devops-toolkit
    initialNodeCount: 1
    config:
      preemptible: true
      machineType: e2-standard-2
      oauthScopes:
      - https://www.googleapis.com/auth/cloud-platform
    autoscaling:
      enabled: true
      minNodeCount: 1
      maxNodeCount: 2
    management:
      autoUpgrade: false
